### PR TITLE
Check PAGE_TEMPLATES setting

### PR DESCRIPTION
**Pull request by jpic**
I made this PR because there was no obvious way to find out if a template was failing and/or non-existant and it made basic_cms look broken, when it was actually a problem from my end ^^

Pretty cool app, thanks for sharing !

### CODE REVIEW

**Comment by jacoor** [comment]
Hello, thanks for this PR. Would you be able to check django1.8 support? Currently travis complains about it. https://travis-ci.org/ArabellaTech/django-basic-cms/jobs/68409215

Thank you!

**Comment by jpic** [comment]
Done ;)

**Comment by jacoor** [comment]
Thank you!

**Comment by jacoor** [comment]
New version released.

**Comment by jpic** [comment]
Congrats B)​

**Pull request merged**
